---
# 2015-06-17 (cc) <paul4hough@gmail.com>
#
- yum: name=bacula-client
- service: name=bacula-fd state=stopped
- template: src=bacula-fd.conf.jinja2 dest=/etc/bacula/bacula-fd.conf backup=yes
- service: name=bacula-fd state=started
